[build]
  publish = "."
  command = "echo 'No build required'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "python -m http.server 8888"
  port = 8888
  publish = "."

